###


POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "email": "kdemian@yandex.ru",
    "username": "demian1"
}
###


POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "demian1",
    "confirmation_code": "2PEE5HI9Y8HT2LTWJVIMBDH00YZVVI"
}
###

POST http://127.0.0.1:8000/api/v1/genres/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY5OTc4MzMxLCJpYXQiOjE2NjY1MjIzMzEsImp0aSI6ImY5ZjA2OWVlZGM1MzQzMjRiODQ5MDIxM2JkM2RkMDNkIiwidXNlcl9pZCI6Mn0.h65Cc62Vny9cClbhcClCMafs843RxiKgPOESybcjqJ8
Content-Type: application/json

{
    "slug": "new_genre1",
    "name": "Action"
}
###

POST http://127.0.0.1:8000/api/v1/titles/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY5OTc4MzMxLCJpYXQiOjE2NjY1MjIzMzEsImp0aSI6ImY5ZjA2OWVlZGM1MzQzMjRiODQ5MDIxM2JkM2RkMDNkIiwidXNlcl9pZCI6Mn0.h65Cc62Vny9cClbhcClCMafs843RxiKgPOESybcjqJ8
Content-Type: application/json

{
    "name": "Movie",
    "year": 2020,
    "description": "Super movie",
    "genre": ["new_genre", "new_genre1"],
    "category": "films"
}
###

GET http://127.0.0.1:8000/api/v1/titles/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY5OTc4MzMxLCJpYXQiOjE2NjY1MjIzMzEsImp0aSI6ImY5ZjA2OWVlZGM1MzQzMjRiODQ5MDIxM2JkM2RkMDNkIiwidXNlcl9pZCI6Mn0.h65Cc62Vny9cClbhcClCMafs843RxiKgPOESybcjqJ8
###

POST http://127.0.0.1:8000/api/v1/categories/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY5OTc4MzMxLCJpYXQiOjE2NjY1MjIzMzEsImp0aSI6ImY5ZjA2OWVlZGM1MzQzMjRiODQ5MDIxM2JkM2RkMDNkIiwidXNlcl9pZCI6Mn0.h65Cc62Vny9cClbhcClCMafs843RxiKgPOESybcjqJ8
Content-Type: application/json

{
    "name": "Songs",
    "slug": "songs"
}
###

GET http://127.0.0.1:8000/api/v1/genres/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY5OTc4MzMxLCJpYXQiOjE2NjY1MjIzMzEsImp0aSI6ImY5ZjA2OWVlZGM1MzQzMjRiODQ5MDIxM2JkM2RkMDNkIiwidXNlcl9pZCI6Mn0.h65Cc62Vny9cClbhcClCMafs843RxiKgPOESybcjqJ8
###

GET http://127.0.0.1:8000/api/v1/titles/
###

GET http://127.0.0.1:8000/api/v1/titles/29
###

PATCH  http://127.0.0.1:8000/api/v1/titles/29/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY5OTc4MzMxLCJpYXQiOjE2NjY1MjIzMzEsImp0aSI6ImY5ZjA2OWVlZGM1MzQzMjRiODQ5MDIxM2JkM2RkMDNkIiwidXNlcl9pZCI6Mn0.h65Cc62Vny9cClbhcClCMafs843RxiKgPOESybcjqJ8
Content-Type: application/json

{
    "category": "songs",
    "year": 1999
}
###

DELETE http://127.0.0.1:8000/api/v1/titles/29/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY5OTc4MzMxLCJpYXQiOjE2NjY1MjIzMzEsImp0aSI6ImY5ZjA2OWVlZGM1MzQzMjRiODQ5MDIxM2JkM2RkMDNkIiwidXNlcl9pZCI6Mn0.h65Cc62Vny9cClbhcClCMafs843RxiKgPOESybcjqJ8
Content-Type: application/json
###

GET http://127.0.0.1:8000/api/v1/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY5OTc4MzMxLCJpYXQiOjE2NjY1MjIzMzEsImp0aSI6ImY5ZjA2OWVlZGM1MzQzMjRiODQ5MDIxM2JkM2RkMDNkIiwidXNlcl9pZCI6Mn0.h65Cc62Vny9cClbhcClCMafs843RxiKgPOESybcjqJ8
Content-Type: application/json