# Generated by Django 2.2.16 on 2022-10-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20221021_2114'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('slug', 'name'), name='unique genre'),
        ),
    ]
