# Generated by Django 2.2.16 on 2022-10-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_remove_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='titles', to='titles.Genre'),
        ),
    ]
