# Generated by Django 2.2.16 on 2022-10-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_auto_20221025_1728'),
        ('titles', '0008_auto_20221024_0515'),
    ]

    operations = [
    ]
