# Generated by Django 2.2.16 on 2022-10-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_merge_20221026_1303'),
        ('titles', '0009_auto_20221023_1104'),
    ]

    operations = [
    ]
