# Generated by Django 2.2.16 on 2022-10-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0015_auto_20221027_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
