# Generated by Django 2.2.16 on 2022-10-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0016_auto_20221027_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id']},
        ),
    ]
